### ISSUE TITLE
usage problems

### ISSUE THREAD

**Issue by abaumfalk** [lxml/lxml-stubs#1]
I would like to use lxml-stubs with my project and had difficulties to set it up. For debugging I constructed a simple testcase:
test.py 
```python
#!/usr/bin/python3
from lxml import etree

e = etree.fromstring("<ROOT/>")
print(etree.tostring(e))
```

Trying to lint this file failed - according to the given usage info I tried:
```bash
$> MYPYPATH=/my/path/to/lxml-stubs/ mypy test.py
test.py:2: error: Skipping analyzing 'lxml': found module but no type hints or library stubs
(...)
```
and
```bash
$> MYPYPATH=/my/path/to/lxml-stubs/lxml-stubs mypy test.py
test.py:2: error: Skipping analyzing 'lxml': found module but no type hints or library stubs
(...)
```

I solved this issue by renaming the inner lxml-stubs folder to lxml:
```bash
$> mv /my/path/to/lxml-stubs/lxml-stubs /my/path/to/lxml-stubs/lxml
$> MYPYPATH=/my/path/to/lxml-stubs/ mypy test.py
Success: no issues found in 1 source file
```

Is this the preferred way to use the stubs or am I missing something? If yes, I would suggest to rename the folder in the repo or update the usage info so that others will not have these problems.

Arno

**Comment by mthuurne** [comment]
I'm running into the same issue. This is what I found out so far:

To use a stub-only package with mypy, it needs to be installed: you cannot just put it in `MYPYPATH`. [Relevant docs.](https://mypy.readthedocs.io/en/latest/installed_packages.html)

In theory it should be sufficient to install directly from the source tree or repo using `pip`, but for some reason the source package generated by `python setup.py sdist` does not actually contain the stubs. As a result, installation doesn't even put an `lxml-stubs` package in `site-packages`.

**Comment by mthuurne** [comment]
I figured out what was causing the installed package to be empty, see #4 for details.
