### ISSUE TITLE
CustomElementClassLookup return type

### ISSUE THREAD

**Issue by AidanWoolley** [lxml/lxml-stubs#11]
You approved my PR #8 a few days ago to add types for `CustomElementClassLookup`.

The `lookup` method of that class, according to [the docs](https://lxml.de/element_classes.html#custom-element-class-lookup) should return a subclass of `ElementBase` or `None`. Because it is returning a class, not an instance of a class, the return type should be `Optional[Type[ElementBase]]`.

This was changed to `Optional[ElementBase]` in c6120e4997aa59535d434b03f1433fdbd1f2fdc9. I think this change should be reverted as it's incorrect according to the documentation and the required implementation of the function.

Thanks for the help and for approving the original PR.

**Comment by scoder** [comment]
Agreed that it should be reverted. @mvantellingen, according to the test logs, `Type` was probably missing from the imports, but was otherwise the correct annotation.

**Comment by mvantellingen** [comment]
Ah yes my bad. Fixed it just now

**Comment by mvantellingen** [comment]
@AidanWoolley i've given you commit access to this repository, feel free to commit to help make this stubs package complete

**Comment by AidanWoolley** [comment]
Thanks very much for the access! I'm working on an RSS client at the moment, so I'll keep adding things as they come up.
