### ISSUE TITLE
No stubs for lxml.html

### ISSUE THREAD

**Issue by egrubbs** [lxml/lxml-stubs#15]
Running `mypy foo.py` with lxml-stubs installed handles `import lxml` fine, but `import lxml.html` reports an error since it is not defined in lxml-stubs.

```
foo.py:2: error: Skipping analyzing 'lxml.html': found module but no type hints or library stubs
foo.py:2: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

foo.py file:
```
import lxml
import lxml.html
```

**Comment by ndfred** [comment]
I am experiencing the same issue

**Comment by scoder** [comment]
PR welcome.

**Comment by djbrown** [comment]
@scoder #20 and #25 seem to adress this issue. could you (or someone else) look into them?

**Comment by scoder** [comment]
Initial (although incomplete) stubs were added.

**Comment by djbrown** [comment]
@scoder thanks for approving :) do you know when you could release it?
thanks for the maintenance ;)

**Comment by scoder** [comment]
Version 0.2.0 is out in the wild.
