### ISSUE TITLE
https://github.com/lxml/lxml-stubs/issues/new

### ISSUE THREAD

**Issue by ITProKyle** [lxml/lxml-stubs#19]
According to the source code, `_Element.find()` should take argument `namespaces`. The stubs for this method contains `namespace` instead.

## Source

https://github.com/lxml/lxml/blob/c053dc159c7f0a6a98922c937a0baede7ce7af9d/src/lxml/etree.pyx#L1521

## Stubs

https://github.com/lxml/lxml-stubs/blob/ca61dcebdc76034240a75374b5a056869bd997e8/lxml-stubs/etree.pyi#L105-L107

**Comment by scoder** [comment]
Thanks
