### ISSUE TITLE
_Element.find has namespaces, not namespace

### ISSUE THREAD

**Issue by pihentagy** [lxml/lxml-stubs#22]
My code runs fine but mypy complains:
```
error: Unexpected keyword argument "namespaces" for "find" of "_Element"; did you mean "namespace"?
error: "_Element" has no attribute "replace"
```
Seems like a typo in the typehint of `find`?

**Comment by scoder** [comment]
Fixed in https://github.com/lxml/lxml-stubs/commit/8f1891e0382958bf4bb916f8d5d4647610aa0287 and https://github.com/lxml/lxml-stubs/commit/d731ff783769c6d6999a2274dea70c203cab09b7
