### ISSUE TITLE
Publishing as package in the cheeseshop

### ISSUE THREAD

**Issue by funkyfuture** [lxml/lxml-stubs#3]
it seems that there's already a [lxml-stubs](https://pypi.org/project/lxml-stubs/) package on the PyPI.

i'm opening this issue because the situation will lead to confusion and the docs should warn about installing this package.

or could the stubs be integrated w/ the `lxml` package?

**Comment by funkyfuture** [comment]
oh, i see that @mvantellingen, the package owner, has been contributing here.

**Comment by mvantellingen** [comment]
Yep. I still need to setup a github action workflow to publish to pypi.

**Comment by mvantellingen** [comment]
I've created the github actions and tested the automated release workflows. When you push a tag you can now draft a release via the interface and it will trigger a github actions to push that to pypi
