### ISSUE TITLE
stub names raise warning

### ISSUE THREAD

**Issue by altaurog** [lxml/lxml-stubs#32]
If I have the following
```
from lxml import etree
tree: etree._ElementTree = etree.parse(file_obj)
```
I get a pylint warning:
`W0212: Access to a protected member _ElementTree of a client class (protected-access)`

I see `_Element` and `_ElementTree` are the lxml names, I gather a workaround is outside the scope of this project?

**Comment by scoder** [comment]
Sure. They are internal classes and not meant to be touched by users. Only their instances should be relevant.

**Comment by altaurog** [comment]
Hey, @scoder thank you very much for the explanation.  I am puzzled, though.  I thought the whole point of type annotations was to document the type of the data objects that are passed around.  So if I am passing or returning an instance of Element or ElementTree, then I need those types for my annotation (as in my example above).  Am I missing something?

**Comment by scoder** [comment]
As internal classes, they were never meant to become a part of type hints. Remember that type hints are optional in Python.

lxml (like that of many other important libraries) predates type hints by almost a decade. Even Py3 annotations were still years away when lxml was first released.

I would argue that `pylint` is wrong in issuing that warning. If what the user declares is the type of the variable, then it's the type of the variable no matter how it's named. `pylint` should be fixed to exclude type hints from that warning (or use a different warning number for it that users can exclude themselves).

**Comment by altaurog** [comment]
yes, fair enough

**Comment by mokko** [comment]
I dont know about pylint, but mypy allows suppressing error messages using comments like this # type: ignore
