### ISSUE TITLE
_ElementTree.find* are missing

### ISSUE THREAD

**Issue by jenstroeger** [lxml/lxml-stubs#33]
Looks like the [`_ElementTree.find()` method](https://lxml.de/apidoc/lxml.etree.html#lxml.etree._ElementTree.find) is missing from the [`_ElementTree` stubs](https://github.com/lxml/lxml-stubs/blob/f3360f43ea7d57e0e2d9cd82d075bd2d51afe011/lxml-stubs/etree.pyi#L169-L212), as well as `findall()` and `findtext()`.

Without actually trying the code, I think
```python
def find(
    self, path: str, namespaces: _OptionalNamespace = ...
) -> Optional["_Element"]: ...
```
would be the appropriate change? Much like the [methods of the same name in `_Element`](https://github.com/lxml/lxml-stubs/blob/f3360f43ea7d57e0e2d9cd82d075bd2d51afe011/lxml-stubs/etree.pyi#L107-L118).

**Comment by scoder** [comment]
The methods were added in https://github.com/lxml/lxml-stubs/commit/08b07a5945cc61d7c1ffe8dc0f76bb07f8cc1515

**Comment by scoder** [comment]
Already reported in #23.
